name: PR checks

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    # Setting shell: bash explicitly activates pipefail
    shell: bash

env:
  CLICOLOR: 1
  DEBIAN_FRONTEND: noninteractive

# These would more naturally be separate jobs, but GitHub actions “bills” each
# job separately and rounds up to the next minute, so four 10 second jobs “cost”
# my account 4 action minutes.
jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      security-events: write # SARIF reporting for zizmor

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - run: sudo apt-get install -yqq zsh
      - name: Install test harness
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: danielparks/zsh-test-harness
          path: harness
          persist-credentials: false
      - uses: taiki-e/install-action@67729d5c413db75907f0ad1e39bb04b9c868ff60 # v2.85.7
        with:
          tool: git-status-vars

      - run: harness/run-tests.zsh --show-output
        if: ${{ !cancelled() }}

      - uses: crate-ci/typos@bee27e3a4fd1ea2111cf90ab89cd076c870fce14 # v1.48.0
        if: ${{ !cancelled() }}
