name: PR checks

on:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    # Setting shell: bash explicitly activates pipefail
    shell: bash

env:
  CLICOLOR: 1
  DEBIAN_FRONTEND: noninteractive

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: sudo apt-get install -yqq zsh
      - name: Install test harness
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: danielparks/zsh-test-harness
          path: harness
      - uses: taiki-e/install-action@6887963ccf37a9ddcd8c5fa4baeb3e1e5fd61fa1 # v2.81.2
        with:
          tool: git-status-vars
      - run: harness/run-tests.zsh --show-output

  typos:
    name: typos
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: crate-ci/typos@f8a58b6b53f2279f71eb605f03a4ae4d10608f45 # v1.47.0
